# Generated by Django 4.0.1 on 2022-04-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('companyname', models.CharField(max_length=255, null=True)),
                ('producttype', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(default='0')),
                ('timetocontact', models.CharField(max_length=255, null=True)),
                ('tranporttype', models.CharField(max_length=255, null=True)),
                ('messege', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('reject_reason', models.CharField(max_length=255, null=True)),
                ('rate', models.CharField(max_length=200)),
                ('shipmentdate', models.DateField(blank=True, null=True)),
                ('from_place', models.CharField(max_length=255, null=True)),
                ('to_place', models.CharField(max_length=255, null=True)),
                ('tracking_status', models.CharField(max_length=255, null=True)),
                ('shipment_status', models.CharField(max_length=255, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('cpassword', models.CharField(max_length=255, null=True)),
                ('joiningdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('photo', models.FileField(blank=True, default='face3.jpg', null=True, upload_to='images/')),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('joiningdate', models.DateField(blank=True, null=True)),
                ('address1', models.CharField(max_length=240, null=True)),
                ('address2', models.CharField(max_length=240, null=True)),
                ('pincode', models.CharField(max_length=240, null=True)),
                ('district', models.CharField(max_length=240, null=True)),
                ('State', models.CharField(max_length=240, null=True)),
                ('salary', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=255, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(max_length=240, null=True)),
                ('bank', models.CharField(max_length=240, null=True)),
                ('accountnumber', models.CharField(max_length=240, null=True)),
                ('ifse', models.CharField(max_length=240, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.order_request')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.user_registration')),
            ],
        ),
        migrations.AddField(
            model_name='order_request',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.staff_registration'),
        ),
        migrations.AddField(
            model_name='order_request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.user_registration'),
        ),
    ]
