# Generated by Django 4.0.1 on 2022-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_registration',
            name='photo',
            field=models.FileField(blank=True, default='blank.jpg', null=True, upload_to='images/'),
        ),
    ]
