# Generated by Django 4.0.1 on 2022-05-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_order_request_user_alter_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(max_length=255, null=True)),
                ('space', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
