# Generated by Django 4.0.1 on 2022-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_request',
            name='storage',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
