# Generated by Django 4.0.1 on 2022-05-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='subject',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
